### ISSUE TITLE
Dev Mode

### ISSUE THREAD

**Issue by harvy4002** [ManchesterSpaceProgramme/ASAPP#1]
Have the ability to activate dev mode which will send out text messages every 5 minutes (or a low amount) instead of the usual 30 minutes. This will allow to iterate much faster on resolving any issues with hardware.

**Comment by davetrencher** [comment]
If you run the debug build (plug in phone and debug through Android Studio) it will run every five minutes.  If you download and install the signed APK it will run every 30 minutes.
